1 stdcall -private DllMain(long long ptr)
2 stdcall XInputGetCapabilities(long long ptr)
3 stdcall XInputGetDSoundAudioDeviceGuids(long ptr ptr)
4 stdcall XInputSetState(long ptr)
5 stdcall XInputGetState(long ptr)
